apiVersion: apps/v1
kind: Deployment
metadata:
  name: sumon
  labels:
    app: sumon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sumon
  template:
    metadata:
      labels:
        app: sumon
    spec:
      containers:
        - name: sumon
          image: 096961528614.dkr.ecr.us-east-1.amazonaws.com/sumon:1.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080